version: '2.4'
services:
    gaan:
        build: .
        volumes:
            - /home/itolab/phamduy/GaAN:/usr/phamduy/
        ## runtimeを指定する！！
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        command: nvidia-smi
